"""add count in OrderProductAss

Revision ID: e8667899cbf0
Revises: a72056a4f48f
Create Date: 2024-08-05 16:04:47.349028

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e8667899cbf0"
down_revision: Union[str, None] = "a72056a4f48f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
    # Удалил до миграции, потому что после count уже было создано
    #     op.add_column(
    #     "order_product_association",
    #     sa.Column("count", sa.Integer(), default=1, server_default="1", nullable=False),
    # )
    # op.create_unique_constraint(
    #     "idx_unique_order_product",
    #     "order_product_association",
    #     ["order_id", "product_id"],
    # )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "idx_unique_order_product", "order_product_association", type_="unique"
    )
    op.create_unique_constraint(
        "index_unique_orders_product",
        "order_product_association",
        ["order_id", "product_id"],
    )
    op.drop_column("order_product_association", "count")
    # ### end Alembic commands ###
