"""current_price add

Revision ID: f5f7e90c9b0b
Revises: 84ec963825b1
Create Date: 2024-08-07 10:56:07.823551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5f7e90c9b0b'
down_revision: Union[str, None] = '84ec963825b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_product_association', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_price', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_product_association', schema=None) as batch_op:
        batch_op.drop_column('current_price')

    # ### end Alembic commands ###
